package com.company.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OwnerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOwnerAllPropertiesEquals(Owner expected, Owner actual) {
        assertOwnerAutoGeneratedPropertiesEquals(expected, actual);
        assertOwnerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOwnerAllUpdatablePropertiesEquals(Owner expected, Owner actual) {
        assertOwnerUpdatableFieldsEquals(expected, actual);
        assertOwnerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOwnerAutoGeneratedPropertiesEquals(Owner expected, Owner actual) {
        assertThat(expected)
            .as("Verify Owner auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOwnerUpdatableFieldsEquals(Owner expected, Owner actual) {
        assertThat(expected)
            .as("Verify Owner relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getGender()).as("check gender").isEqualTo(actual.getGender()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOwnerUpdatableRelationshipsEquals(Owner expected, Owner actual) {
        // empty method
    }
}
